### ISSUE TITLE
array[i].method() gives a syntax error

### ISSUE THREAD

**Issue by alias-nicole** [davecparker/code12#112]
```
import Code12.*;

class TestProgram extends Code12Program
{
   String[] arr;

   public static void main(String[] args)
   { 
      Code12.run(new TestProgram()); 
   }
   
   public void start()
   {
      arr = new String[3];
      arr[0] = "small";
      arr[1] = "medium";
      arr[2] = "largest";
      
      for( int i = 0;  i < arr.length - 1;  i++ )
      {
         if ( arr[i].length() < arr[i+1].length() )
            ct.println( arr[i] + " is shorter than " + arr[i+1] );
      }
   }
  
}
```

The if statement header comparing the length of two adjacent strings within a string array generates a "Syntax Error" on the Corona app. I'm not sure if this is something that needs fixing, or if users will primarily be using Java's compareTo() method instead of the relational operators <, >, <=, etc.

**Comment by davecparker** [comment]
Yes I want to fix this, to add support for array[i].method(), which the syntax currently doesn't support.

**Comment by davecparker** [comment]
Should be fixed as of 6/30 pull request.

**Comment by alias-nicole** [comment]
verified fix in various tests with string arrays.
