### ISSUE TITLE
Hit tests for rects and circles don't take their line width into account

### ISSUE THREAD

**Issue by bcauchon** [davecparker/code12#113]

**Comment by bcauchon** [comment]
Same also for non-parallel slanted lines.

**Comment by davecparker** [comment]
We don't have to fix this unless it turns out to be easy and efficient. Can leave it open until you decide.

**Comment by bcauchon** [comment]
I don't think it would be too difficult for non-line objs, but would slightly reduce efficiency through having to access their lineWidth fields and g.scale and some additional arithmetic operations when calculating their bounding rects; slanted lines would probably be a little trickier and require a reworking of the algorithm in the hitObj method for lines.
I don't think it's worth it since students aren't likely to used super thick line widths together with obj1.hit(obj2). If we end up with performance issues from line.hit(obj) in the future we could probably even take line width considerations out of hitObj for horizontal and vertical lines without noticeable effects in most common use cases (e.g. lines as bullets/lasers hitting image targets).
