### ISSUE TITLE
ct.clickX() and ct.clickY() operate differently with Lua than Java

### ISSUE THREAD

**Issue by alias-nicole** [davecparker/code12#114]
With Java, these functions can return the coordinates of the last known click OR drag -- with Lua, they return only the coordinates of the last known click (even when used within the onMouseDrag() event ).

**Comment by davecparker** [comment]
I went ahead and updated the Lua side to match the Java side and the docs:
ct.clickX() and ct.clickY() will now also report the last mouse drag location.

**Comment by alias-nicole** [comment]
Fix verified (with my Events White Box Test)
