### ISSUE TITLE
ct.inputBoolean(): Runtime error

### ISSUE THREAD

**Issue by alias-nicole** [davecparker/code12#116]
```
import Code12.*;

class InputTest extends Code12Program
{

   public static void main(String[] args)
   { 
      Code12.run(new InputTest()); 
   }
   
   public void start()
   {
      ct.inputString("Enter a string: ");
      String input = ct.inputString("Enter another string: ");
      ct.inputInt("Enter an integer: ");
      int i = ct.inputInt("Enter another integer" );
      ct.inputNumber("Enter a number: ");
      double d = ct.inputNumber("Enter any number: ");
      ct.inputBoolean("Enter a boolean value: ");
      boolean bool = ct.inputBoolean("Enter another boolean value " );
   }
   
}
```

Attached is a screenshot of the runtime error given when ct.inputBoolean() is encountered. The prompt to enter a boolean value isn't displayed, either. I looked through text.lua, but the other functions( ct.inputInt(), etc.) make calls to inputLine as well, so I'm unsure of the cause.
(I included the other input methods to ensure that those work.)
<img width="293" alt="inputbool" src="https://user-images.githubusercontent.com/38896487/42122035-5b42ce1a-7bf0-11e8-8698-bbfda0d9f182.PNG">

**Comment by davecparker** [comment]
Oops, should have been inputLine, not ct.inputLine in the code.

**Comment by alias-nicole** [comment]
verified fix.
