### ISSUE TITLE
Input in start function causes initial screen to be drawn wrong.

### ISSUE THREAD

**Issue by bkainoa** [davecparker/code12#125]
Before input
![before draw](https://user-images.githubusercontent.com/14100816/42245183-ad80d102-7ecc-11e8-8f20-f2b1a2695330.PNG)

After input
![after input](https://user-images.githubusercontent.com/14100816/42245189-aef018a4-7ecc-11e8-8bc3-bfcd9142d233.PNG)

**Comment by davecparker** [comment]
I think this will be fixed now, can you try it out.
