### ISSUE TITLE
Decimals without leading zeros generate a syntax error

### ISSUE THREAD

**Issue by bcauchon** [davecparker/code12#128]
E.g.
x = .5;
x = -.5;

**Comment by davecparker** [comment]
I'll give this one to you. I'll show you where in the lexer it needs to go.

**Comment by bcauchon** [comment]
Fixed in [afe72e5](https://github.com/davecparker/code12/commit/afe72e5e04630032af54ab25318ca1fe842f723a)

**Comment by davecparker** [comment]
Verified in UserCode.java locally on my branch.
