### ISSUE TITLE
Overloaded function not caught as previously defined.

### ISSUE THREAD

**Issue by bcauchon** [davecparker/code12#129]
// with the following function definitions (from MathMiscTypeConversionTest.java):

public void testFormatDecimal( double d, String expected )
   {
      String output = ct.formatDecimal( d );
      if ( !output.equals(expected) )
         printError( "ct.formatDecimal(" + d + ") = " + output + "; " + expected + " expected" );
   }
   
   public void testFormatDecimal( double d, int numPlaces, String expected )
   {
      String output = ct.formatDecimal( d, numPlaces );
      if ( !output.equals(expected) )
         printError( "ct.formatDecimal(" + d + ", " + numPlaces + ") = " + output + "; " + expected + " expected" );
   }

// and then the following function call:
         testFormatDecimal( 0.0, "0.0" );

// Results in syntax error: Not enough parameters passed to testFormatDecimal (requires 3)

**Comment by davecparker** [comment]
Now checking for this and not allowing any re-defined functions. My noobs will not know about overloading yet, so I just call it attempting to redefine an existing function.

**Comment by bcauchon** [comment]
Fix verified.
