### ISSUE TITLE
onMouseDrag(): Corona Runtime Error 

### ISSUE THREAD

**Issue by alias-nicole** [davecparker/code12#131]
<img width="296" alt="error" src="https://user-images.githubusercontent.com/38896487/42350746-a54c3d28-8066-11e8-979a-ae78431d67c7.PNG">

<img width="569" alt="onmousedrag" src="https://user-images.githubusercontent.com/38896487/42351006-c3219144-8067-11e8-935a-26493b886c01.PNG">

If clicks are not being passed through an if statement such as if ( obj != null ) to check if the click occurred on an object, users can effectively draw on blank/null space, including outside of the program pane.

**Comment by davecparker** [comment]
Should be fixed now. Your samples don't run for me directly because they have minor syntax errors, etc. that I think you have fixed on your machine, so can you do a pull request soon so we can get your fixes and other improvements, thanks!

**Comment by alias-nicole** [comment]
Verified fix. This also fixed the issue with dragging the cursor and the pane resizing simultaneously.
