### ISSUE TITLE
ct.showAlert() used in Event functions: Execution of the program does not pause right away

### ISSUE THREAD

**Issue by alias-nicole** [davecparker/code12#139]
When called from onMousePress(), the running program does not halt properly (e.g., moving objects in the background keep moving despite the alert dialogue box).

**Comment by davecparker** [comment]
This should be fixed now. Although the user's code was pausing, if you used GameObj.xSpeed and ySpeed then those were still being applied every frame during the wait.

**Comment by alias-nicole** [comment]
Verified fix.
