### ISSUE TITLE
Int output in Math class on lua side

### ISSUE THREAD

**Issue by landonfox00** [davecparker/code12#146]
All Math class methods that have both a double and int variant return a double output even when given ints exclusively on the lua side. Methods include:
> int Math.abs( int a )
> int Math.max( int a, int b )
> int Math.min( int a, int b )

![capture](https://user-images.githubusercontent.com/23734685/42674747-c9ed95f4-8625-11e8-837a-87b1a232ddac.PNG)

**Comment by davecparker** [comment]
Now handling special case for Math.abs, Math.min, and Math.max, which is if you pass all ints, it returns int, otherwise it returns double.
