### ISSUE TITLE
Hitting TextObj in lua

### ISSUE THREAD

**Issue by landonfox00** [davecparker/code12#147]
When an object reaches the same y coordinate value as a TextObj, the hit method returns true. This applies in the case of obj.hit(TextObj) and TextObj.hit(obj).

**Comment by landonfox00** [comment]
This applies even when the TextObj's text is not changed since its initialization.

**Comment by davecparker** [comment]
Simple bug where previous width/height were not initialized properly, leading to bogus width calculation.
