### ISSUE TITLE
Unrecognition of String variable named string within functions

### ISSUE THREAD

**Issue by landonfox00** [davecparker/code12#148]
String variables named "string" within functions get flagged as mistyped names known as "String."
For instance:
```
public String charAt(String string, int i)
{
    if (string.length() == 0)
        return "";
    if (i == string.length())
        return string.substring(i);
    return string.substring(i, i + 1);
}
```

![capture2](https://user-images.githubusercontent.com/23734685/42710209-ed34ee78-8697-11e8-8cae-07ea8e3da568.PNG)

**Comment by davecparker** [comment]
Now checking for invalid variable and function names that either match type names (those were allowed before, oops) or differ only by case from a type name. So, the above code is not allowed in Code12, but the error message is much better now. There are several other similar cases involving variable and function names that are fixed as well.
