### ISSUE TITLE
Corona Simulator on Windows: Upon launch of the Code12 app, the full path name to the java file is displayed

### ISSUE THREAD

**Issue by alias-nicole** [davecparker/code12#156]
<img width="301" alt="capture" src="https://user-images.githubusercontent.com/38896487/42969971-d2a76580-8b5c-11e8-8dc1-388dbecf8df5.PNG">

**Comment by davecparker** [comment]
Finally removed the hack to start with my default testing file, and now the desktop app remembers and restores the last source file you used. Much more useful :)

**Comment by alias-nicole** [comment]
Verified fix
