### ISSUE TITLE
Type checking numeric literals in exponential notation.

### ISSUE THREAD

**Issue by bcauchon** [davecparker/code12#158]
int i = 12e10; // Passes Error Test
int i = 3.42e2; // Fails Error Test: "Value of type double cannot be assigned to an int, use ct.round() or ct.toInt()"

**Comment by davecparker** [comment]
Sticking with being a subset of Java... I now consider all uses of exp notation to be double, regardless of value.

**Comment by bcauchon** [comment]
Fix verified in ErrorTestCode.java
