### ISSUE TITLE
Calling ct methods before start possible from user defined functions, crashes desktop app.

### ISSUE THREAD

**Issue by bcauchon** [davecparker/code12#167]
```
import Code12.*;

class TestProgram extends Code12Program
{
	
	public static void main(String[] args)
	{ 
		Code12.run(new TestProgram()); 
	}
	
	public void start()
	{
	}
	
	public void update()
	{	
	}
	
 	GameObj newRect()
 	{
 		return ct.rect(50,50,10,10);
 	}
 	GameObj r = newRect();

}
```

**Comment by bcauchon** [comment]
ERROR: Runtime error
C:\Users\bcauc\Documents\GitHub\code12\Desktop\Code12\Code12\objects.lua:44: attempt to index field 'screen' (a nil value)
stack traceback:
	C:\Users\bcauc\Documents\GitHub\code12\Desktop\Code12\Code12\objects.lua:44: in function <C:\Users\bcauc\Documents\GitHub\code12\Desktop\Code12\Code12\objects.lua:33>
	(tail call): ?
	[string "..."]:23: in function 'codeFunction'
	C:\Users\bcauc\Documents\GitHub\code12\Desktop\Code12\main.lua:56: in function 'runLuaCode'
	C:\Users\bcauc\Documents\GitHub\code12\Desktop\Code12\main.lua:215: in function 'processUserFile'
	C:\Users\bcauc\Documents\GitHub\code12\Desktop\Code12\main.lua:233: in function '_listener'
	?: in function '?'
	?: in function <?:190>

**Comment by davecparker** [comment]
Calls to ct APIs or user functions are now disallowed in instance variable init expressions, because otherwise we cannot guarantee that ct will be initialized. Also instance variables must now be put before all functions/methods, so that the resulting Lua code will work.

**Comment by bcauchon** [comment]
Fix verified on master
