### ISSUE TITLE
Corona becomes unresponsive when setting clickable to false

### ISSUE THREAD

**Issue by landonfox00** [davecparker/code12#168]
If an GameObj is clicked and its clickable field is set to false, the Corona Simulator becomes unresponsive.

```
import Code12.*;

public class Test extends Code12Program
{
    GameObj testRect;

    public static void main(String[] args)
    {
        Code12.run(new Test());
    }

    public void start()
    {
        testRect = ct.rect(50, 50, 10, 10);
    }

    public void update()
    {
        if (testRect.clicked())
            testRect.clickable = false;
    }
}
```

**Comment by davecparker** [comment]
I had to make a low-level change in the event handling to fix this, so if you could test related stuff with clicking objects, getting mouse down, drag, and release events, and the clickable field, that would be great, thanks.
