### ISSUE TITLE
Infinite loops hang the app

### ISSUE THREAD

**Issue by landonfox00** [davecparker/code12#176]

**Comment by davecparker** [comment]
Possible solution:
CodeGen inserts a function call ct.checkFrame() into all loops.
ct.checkFrame() checks to see if the current frame interval has expired (the next frame is overdue), and if so then it yields to the runtime, which then recognizes this condition and returns to Corona to allow the next frame, UI button listeners, etc. The next update then resumes the yielded user coroutine.

**Comment by davecparker** [comment]
Loops now generate a call to ct.checkFrame(), which yields back to the main app if the current animation frame lasts longer than 20 ms (50 fps) but keeps running, and prints a warning if the loop runs longer than 3 seconds.

**Comment by davecparker** [comment]
Verified with new test app Java/Test Apps/Array Tests/ForEachTest.java.
