### ISSUE TITLE
Error when lua code fails to load

### ISSUE THREAD

**Issue by alias-nicole** [davecparker/code12#177]
The user interface sort of freezes, in that the user's program is still stuck at a previous state/level and the error message isn't updated.

Example in screencap:
<img width="300" alt="corona" src="https://user-images.githubusercontent.com/38896487/43806084-5396c4c0-9a57-11e8-9cc8-af00c00ad3eb.PNG">
:

**Comment by davecparker** [comment]
Unexpected code generation errors should now be reported gracefully in the UI, and usually with the line number that caused them highlighted.

**Comment by alias-nicole** [comment]
Verified fix.
