### ISSUE TITLE
Expression parsing error

### ISSUE THREAD

**Issue by alias-nicole** [davecparker/code12#180]
velocityY = jumpVelocity * (1.0 - (double)Math.Pow(jumpTime / maxJumpTime, jumpPower));

The error in this statement is the attempt at explicit type-casting.
         
<img width="302" alt="expr" src="https://user-images.githubusercontent.com/38896487/43932403-c24b1450-9bf8-11e8-85ef-a4a737679504.PNG">

**Comment by davecparker** [comment]
This motivated me to add parsing support for type casts, although the only type cast allowed by the semantic checking is (int).
