### ISSUE TITLE
code12 API docs: ct.getWidth()

### ISSUE THREAD

**Issue by alias-nicole** [davecparker/code12#184]
### ct.getWidth()
This function always returns 100.0, which is the width of the application window in coordinate units by definition. *This is the maximum x-coordinate that is inside the window (the right edge).*

-- Possibly reword this second statement, in order to avoid possible confusion (i.e.,  the max x-coordinate changes when ct.setScreenOrigin() is used.

**Comment by davecparker** [comment]
Cleaned up the description of ct.getWidth(), ct.getHeight(), and ct.setHeight() in API.md.
