### ISSUE TITLE
Code12Program should be a reserved identifier

### ISSUE THREAD

**Issue by bkainoa** [davecparker/code12#195]
Currently Code12Program is not a reserved identifier and is usable as a class name, variable name ect.

**Comment by davecparker** [comment]
The class name is now checked to not be a pre-defined Code12 class name or any of the very common class names pre-defined in java.lang (see isKnownClassName in javatypes.lua). Also we check that it starts with a capital letter (enforced convention). 
A different recent change disallows variable, function, and parameter names starting with an upper-case letter, so the class name is the only name directly affected by this fix.
