### ISSUE TITLE
Declaration of multiple arrays as a single statement crashes app

### ISSUE THREAD

**Issue by bcauchon** [davecparker/code12#201]
```
import Code12.*;
class TestProgram extends Code12Program
{
	GameObj[] coins, walls;

	public static void main(String[] args)
	{
		Code12.run(new TestProgram()); 
	}
	
	public void start()
	{
		coins = new GameObj[10];
		walls = new GameObj[4];
		ct.log(coins, walls);
	}
}
```
ERROR: Runtime error
C:\Users\bcauc\Documents\GitHub\code12\Desktop\Code12\parseProgram.lua:313: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
	[C]: in function 'ipairs'
	C:\Users\bcauc\Documents\GitHub\code12\Desktop\Code12\parseProgram.lua:313: in function 'getVar'
	C:\Users\bcauc\Documents\GitHub\code12\Desktop\Code12\parseProgram.lua:830: in function 'getMembers'
	C:\Users\bcauc\Documents\GitHub\code12\Desktop\Code12\parseProgram.lua:1032: in function 'getProgramTree'
	C:\Users\bcauc\Documents\GitHub\code12\Desktop\Code12\main.lua:190: in function 'processUserFile'
	C:\Users\bcauc\Documents\GitHub\code12\Desktop\Code12\main.lua:236: in function '_listener'
	?: in function '?'
	?: in function <?:190>

**Comment by davecparker** [comment]
Oops, broke that recently. Just slipped the fix into my recent pull request.

**Comment by bcauchon** [comment]
Fix verified on master
