### ISSUE TITLE
Negative height in GameText creation

### ISSUE THREAD

**Issue by landonfox00** [davecparker/code12#217]
Initializing a GameText with a non-positive value in both the lua and java runtime result in odd sizes.

Lua:
![capture](https://user-images.githubusercontent.com/23734685/45246189-cabc5e00-b2b4-11e8-8d8a-4293d8c2dc9f.PNG)

Java:
![capture2](https://user-images.githubusercontent.com/23734685/45246193-cf811200-b2b4-11e8-8e8a-5eb7a3bd577d.PNG)

**Comment by davecparker** [comment]
Negative height now results in a runtime warning printed in red to the console and 0 height used.

**Comment by landonfox00** [comment]
When the height is 0, it appears to result in a height of around 3 maybe. Is this what's expected? I apologize for not clarifying in the original post.
