### ISSUE TITLE
Nan value results in the value 5 in java runtime

### ISSUE THREAD

**Issue by landonfox00** [davecparker/code12#221]
Initializing a GameObj with x or y coordniate values results in the value 5 in the java runtime.

```
ct.line(0, 5, 100, 5);
ct.line(5, 0, 5, 100);
ct.circle(nan, 50, 10);
ct.circle(50, nan, 10);
ct.circle(50, 50, nan);
ct.circle(nan, nan, nan);
```

![image](https://user-images.githubusercontent.com/23734685/45246873-af535200-b2b8-11e8-86d2-7d6b885675e6.png)

**Comment by davecparker** [comment]
Fascinating, not important enough to fix, though. The Java runtime is our "graduated from Code12" mode, and at some point you get what you get :)
