### ISSUE TITLE
Null passed as a color in GameObj intilization gives default color

### ISSUE THREAD

**Issue by landonfox00** [davecparker/code12#249]
When a GameObj is being initialized, if the color parameter is null, the fill color defaults to its original color. This example results in a red fill color.
```
ct.circle(50, 50, 10, null);
```

**Comment by davecparker** [comment]
This is tricky to fix cleanly in the Lua runtime, so I think this is OK as-is. The alternative is to treat it as an invalid color in which case you would get gray, but I think the default color is just as reasonable here.
