### ISSUE TITLE
Add a way to offset the screen origin?

### ISSUE THREAD

**Issue by davecparker** [davecparker/code12#25]
Should we add a way to offset the origin of a screen, to make scrolling games easier to implement?

But... scrolling games typically have UI elements that don't want to move, so perhaps:

ct.setScreenOrigin( x, y )
ct.setScreenOrigin( x, y, groupName ) 

affecting the current screen.
if groupName is included then objects in that group are not affected by the origin (e.g. a UI overlay)

**Comment by alias-nicole** [comment]
Verified this; test game in latest commit.
