### ISSUE TITLE
Support polled input when paused

### ISSUE THREAD

**Issue by davecparker** [davecparker/code12#262]
It would be cool if basic polled mouse and keyboard input worked (e.g. ct.objectClicked(), ct.charTyped()) worked when the game was paused, and took effect when the game was resumed or stepped.

**Comment by davecparker** [comment]
This now works :) Polled input (ct.clicked() and other ct input functions) now report the last click or key typed during a paused state. Event functions are not called when paused, however. 
This also fixes a bug where key press/release state got confused if an input dialog was put up while key(s) were held down and the key(s) were released while the dialog was up.

I updated the original DuckHunt to use polled clicks instead of the onMousePress event, and now it supports this, but not the other two DuckHunts.

**Comment by bcauchon** [comment]
Fix verified on master with DuckHunt and BasicTest.
