### ISSUE TITLE
Need Windows app icon

### ISSUE THREAD

**Issue by davecparker** [davecparker/code12#270]
I added an image file "app-icon.png" to Desktop/Code12 to use as the app icon (at least for now). I also generated the required Mac OS icon file "Icon-osx.icns". Now we need the Windows version, which needs to be called "Icon­-win32.ico" in Windows icon format. See:
https://docs.coronalabs.com/guide/distribution/win32Build/index.html#appicon

Can you find a tool that can convert the png (which is 1024x1024 with transparency) to Windows icon format and add it. Visual Studio can probably do it, as can various other utilities.

**Comment by bcauchon** [comment]
I made the Windows icon manually using GIMP2. Should I also write a script to generate it from app-icon.png?

**Comment by davecparker** [comment]
An app icon file should have multiple sizes/resolutions of the icon embedded in it, so the goal is a process that makes it reasonably easy to get all the different sizes and perhaps re-create them all from the source png file if we change the icon in the future. I doubt there is a way to do it from script on Windows, so you will need an app tool. Here's one method described that is semi-manual:
http://zduck.com/2014/creating-ico-icon-for-windows-app/

**Comment by davecparker** [comment]
Sure, that should be fine. As far as I know it's not possible to infect an ICO with something nefarious.

**Comment by bcauchon** [comment]
Did some testing and found that Windows was using the 48x48 resolution png for the taskbar. I remade that file with GIMP from app-icon.png and rebuilt the Icon-win32.ico using [Icon Maker](https://github.com/Inedo/iconmaker). This seems to have fixed the blurryness in the taskbar icon.
