### ISSUE TITLE
Visual Tweaks: getFile

### ISSUE THREAD

**Issue by davecparker** [davecparker/code12#271]
Some visual tweaks for the getFile screen:

1. Let's try a white background. The gray is a little dreary for a welcome screen.

2. Text objects in Corona will appear fuzzy if drawn starting at a non-integer x or y pixel location. You can see the various text objects in getFile appear fuzzy or not as you resize the window and they re-center. I have been battling this issue throughout the app and FYI also fixed an instance of this recently in varWatch. Basically, you always want to use top-left alignment (not default center, compute your own centering as necessary if desired), and if it's possible for a coordinate to be non-integer (e.g. you compute it by dividing or by multiplying by an average char width), then you need to round it before using it as a Corona display coordinate.

3. Text of "Also Open in Text Editor" looks too large (and the checkbox). Maybe start with same font size as the recent filenames and try that. But then perhaps add some vertical space to move this farther away from the recent file list.

**Comment by bcauchon** [comment]
Should be fixed in pull request #298
