### ISSUE TITLE
Toolbar icons aren't scaling well

### ISSUE THREAD

**Issue by davecparker** [davecparker/code12#272]
Some of the toolbar icons don't look good scaled down to their size as used. Some suggestions to try:

1. It looks like your icon size is currently 15x15. I think you will get better results with a more natural multiple such as 16x16.

2. It would be good if the source of the icons is a multiple of the size you intend to display at (e.g. 256x256 is common).

3. If the above is not good enough, you could re-create all the icon files at the exact resolution we will use (e.g. 16x16 and tweak the pixels manually), or probably better twice (e.g. 32x32) for double-res screens. Although nowadays, some screens will scale at non-doubling factors, so probably approach #2 is better in general if it will work.

**Comment by bcauchon** [comment]
Fixed in #298
