### ISSUE TITLE
Visual tweaks: optionsView

### ISSUE THREAD

**Issue by davecparker** [davecparker/code12#273]
Some visual tweaks for the Options view:

1. (Light gray background is fine here I think, no change needed)

2. All text except the title "Code12 Options" seems too large. Let's try for something closer to the system font size used in system dialogs or perhaps a tad larger.

3. All text needs to be aligned to integer pixels (see related #271)

4. Checkbox and radio button icons probably need to be tweaked to scale better (see related #272)

5. More space needed between sections.

6. Don't need colons after section headers if they are bold.

7. Change "Syntax Level" to "Java Language Syntax Level"

8. Change "Tab Width" to "Tab Width for Source Code Display"

9. Change "Variable Watch Mode" to "Program View"

10. Capitalize "Show the Variable Watch Window"

11. Try indenting "Add a Text Editor" button to line up with the editor names, and less margin in the button outline.

12. Keep "Open MyProgram.java in Editor" not indented

13. The X button is too subtle. Let's try a toolbar-style button with X icon and "Close" text in blue, button frame, etc.

**Comment by davecparker** [comment]
Looked at new results on Mac. The font size now seems a bit small and smaller than normal system UI font. I tried setting app.optionsFontSize to 14 and that seemed pretty good.

Also, text and everything is alternately fuzzy or not as it re-centers when the window is resized both in x and y, so there is probably still some non-integer stuff going on in options. But getFile looks fine. Maybe one of the intermediate groups or scrollView? Or something is still center aligned not top-left?

**Comment by bcauchon** [comment]
Fixed in #289 and #298
