### ISSUE TITLE
Clicking a clickable line makes Lua runtime unresponsive to any further clicks.

### ISSUE THREAD

**Issue by bcauchon** [davecparker/code12#277]
Bug doesn't occur on Java runtime or if line.setClickable( false ) is called.

Can be seen using BasicText.java or the following text program.
'''
import Code12.*;
public class ObjClickedTest extends Code12Program
{
	GameObj textObj;

	public void start()
	{
		ct.line( 0, 0, 100, 100 ); // diagonal
		ct.line( 100, 0, 0, 100 ); // diagonal 
		ct.line( 0, 50, 100, 50 ); // horizonal
		ct.line( 50, 0, 50, 100 ); // vertical
		GameObj redLine = ct.line( 0, 50, 50, 0, "red" );
		redLine.setClickable( false );
		ct.rect( 25, 50, 20, 10 );
		ct.circle( 75, 50, 10 );
		ct.image( "treasure.jpg", 50, 25, 10 );
		textObj = ct.text( "CLICK ME", 50, 75, 5 );
		textObj.setSpeed( .5, 0 );
	}

	public void update()
	{
		if ( ct.objectClicked() != null )
			ct.logm( "clicked", ct.objectClicked() );
		else if ( ct.clicked() )
			ct.println( "click" );

		if ( textObj.x > 110 ) 
			textObj.x = -10;
	}

	public static void main(String[] args)
	{
		Code12.run(new ObjClickedTest());
	}
}

**Comment by davecparker** [comment]
My recent runtime optimizations broke this. Lines replace their display object whenever sized, and this caused the touch event listener to not carry over to the new one. Now doing it explicitly.

**Comment by bcauchon** [comment]
Fix verified on main branch.
