### ISSUE TITLE
Make installer for Windows

### ISSUE THREAD

**Issue by davecparker** [davecparker/code12#287]
It would be good to have an installer for the Windows app. Our install is quite simple, so hopefully it won't be too complex. Basically we just want the folder with the EXE and the DLLs and such copied to a "Program Files\Code12" folder and a desktop shortcut to the code12.exe added. Ability to uninstall would be good, which could be either via a link in All Programs, or perhaps just make sure it works to do it from Settings/Control Panel. These are standard things that a decent tool should do for you.

A basic choice is an installer exe (self-extracting exe), vs. an msi (standard Microsoft Installer package). Network admins prefer msi, but they are generally more complex to build I think.

Here are 3 options for making an installer .exe:
https://www.makeuseof.com/tag/how-to-make-an-exe-installation-file/

For making an msi, there are apparently a bunch of ways but perhaps no slam dunk obvious choice.
Microsoft apparently recommends 
http://wixtoolset.org/
which is a script-based method where you code your instructions in XML (good for repeated re-builds, but probably has a learning curve compared to a GUI solution).
It looks like a popular GUI tool is:
https://www.advancedinstaller.com/

Here is one guy giving a brief overview of some of the free options overall:
https://helpdeskgeek.com/free-tools-review/4-tools-to-create-windows-installer-packages/

If you have time, perhaps you can experiment and try to get something for version 1.0. Maybe start with a self-extracting exe  made from Inno Setup to begin with, then eventually if you could find an easy way to get a simple msi that would be great. Maybe one of the MSI tools has an example template for a super-simple app like ours that you could just tweak?

Also, take a look through Corona's build advice at:
https://docs.coronalabs.com/guide/distribution/win32Build/index.html
and see if there are some settings and stuff we should be handling better.
Not sure if we need to code-sign, but I suppose it would be good eventually.

**Comment by bcauchon** [comment]
I used Inno Script Studio to make code12/Desktop/Widows build/Code12Setup.iss.
Open in Inno Script Studio Wizard and select Project > Compile (Ctrl+F9) to build installer Code12Setup.exe.

**Comment by bcauchon** [comment]
#293
