### ISSUE TITLE
Replace uses of ct.toInt() with (int) type cast

### ISSUE THREAD

**Issue by davecparker** [davecparker/code12#297]
The ct.toInt() API has been removed. Several sample and test apps still use it, and I think many of the uses were originally in your sample or test code. Can you search and replace these with an (int) type cast across the project.

**Important**: Note that the ct.toInt() function still exists internally (in api.lua), and Lua code generation still generates calls to it (for a (int) type cast in Java). So when you do a search across all files in the project, you will find a legit hit in api.lua and also hits in .lua files that were written by the code generator. These don't need to be replaced, but the source Java files need to make sure they use (int) instead. You can go ahead and delete generated .lua files when you find them in the project if you want, as this will be a future feature that works differently, and there is no need for the generated lua files to be in the git project.

**Comment by bcauchon** [comment]
Fixed in #300
