### ISSUE TITLE
File toolbar button should probably always be enabled

### ISSUE THREAD

**Issue by davecparker** [davecparker/code12#311]
The File toolbar button should probably always be enabled (or at least enabled whenever Options is), and automatically stop the running program if any.

Default program width should be enough to also show Grid button.

**Comment by davecparker** [comment]
Now you can more easily switch programs (don't need to press Stop first), and beginners won't be confused that they can't find the File button.

This changed turned out to be trivial because `onChooseProgram()` in toolbar.lua, which I renamed to `onFile()`, was already calling `runtime.clearProgram()`, which calls `runtime.stop()`, so it was just a matter of letting the File button be enabled during the running and paused states.

I also remade the File button icon, now renamed `file-icon.png` to make it hollow and with cleaner lines. The icon image is 256x256 like the others, and the line widths are 8 pixels, so they scale down to exactly 1 pixel at 16x16.

Give it a try and see if you can find something wrong that I might have missed.

**Comment by bcauchon** [comment]
Looks good.
