### ISSUE TITLE
Alert in input event hangs program if there is no update function

### ISSUE THREAD

**Issue by davecparker** [davecparker/code12#314]
If an input event function (e.g. onMousePress) shows an alert (which then yields), the runtime does not resume properly if there is no update function in the program.  For example:
```
class Example
{
	public void start()
	{
		ct.println( "start" );
	}

	// public void update()
	// {
	// 	ct.println( "update" );
	// }

	public void onMousePress( GameObj obj, double x, double y)
	{
		ct.println( "onMousePress" );
		ct.showAlert( "Mouse was pressed" );
		ct.println( "Back from alert" );
	}
}
```

**Comment by davecparker** [comment]
Can you help test around this change to get another pair of eyes on it.

I had to make a change to the core enterFrame listener in the runtime to fix this, which is a tad scary, but I convinced myself it was correct... Once start() finishes, onNewFrame in runtime.lua thought its only job was to run update(), but also it needs to resume yielded event listeners (coRoutineUser), which it was already prepared to do and doing in other cases, but there was a check that if update() is nil then skip it. I removed this check and let the lower-level functions correctly figure out what to do, and that logic appeared correct.

**Comment by bcauchon** [comment]
Fix confirmed with Java/Misc Tests/AlertInInputEventTest.java
