### ISSUE TITLE
Empty for loops result in code gen fail

### ISSUE THREAD

**Issue by landonfox00** [davecparker/code12#315]
In the code12 app (1.0), for loops that have no executable code result in the error:
> This line caused an unexpected code generation error

Referring to the line that the for loop header lies.
```java
for (int i = 0; i < 5; i++)
{
}
```

**Comment by davecparker** [comment]
Nice bug find! I was using semicolon in the Lua code generation to separate the last loop stmt from the increment stmt (so they can be on the same line), but if there are no loop stmts then you get a Lua syntax error for the semicolon. The semicolon is not required by Lua and was just for readability in the generated code, so now I just put 2 spaces in there instead, which Lua is fine with.
