### ISSUE TITLE
Math.pow returns nan when exp is less than one

### ISSUE THREAD

**Issue by landonfox00** [davecparker/code12#323]
The Math.pow method returns what appears to be a NAN value when the first argument is less than 0 and the second argument (exponent) is less than 1. As an example:
> ct.isError(Math.pow(-1, 1 / 3.0));

The line above returns true. I believe this could be fixed with something resembling this:
```
if base < 0 and -1 < exponent < 1 and the last digit of exponent is odd then
  return nan 
```

This can also be seen in my graphing utility:

![capture](https://user-images.githubusercontent.com/23734685/50805947-6da7d780-12a9-11e9-935a-f5bb3b1dbb2d.PNG)

**Comment by davecparker** [comment]
Can you clarity what you expect it to do? Are you saying Java and Lua are inconsistent? We're just calling the Java and Lua math libraries internally. Isn't this as-designed by Math.pow?
