### ISSUE TITLE
Add ability to adjust font size for projectors, etc.

### ISSUE THREAD

**Issue by davecparker** [davecparker/code12#324]
For a teaching using a projector in large classroom, as well as accessibility, it would be good to be able to increase the font size used for console output, source code errors, and the varWatch window.  These currently all use `app.consoleFontSize`. Perhaps an option in Options screen to choose from 4-5 sizes.

**Comment by davecparker** [comment]
You could try Corona's native.showAlert() instead of the tinyfiledialogs alert for the restart alert and see if that looks or centers better (try both Mac and Windows).

**Comment by benjbc** [comment]
Enhancement added in pull request #375 and #385

**Comment by davecparker** [comment]
Font sizes 12 and 18 are causing alignment problems with the yellow source code highlight. See new bug #392.

**Comment by davecparker** [comment]
Other than new bug #392, this appears to work on both Mac and Windows, so closing this.
