### ISSUE TITLE
New Program doesn't work on some Windows machine(s)

### ISSUE THREAD

**Issue by davecparker** [davecparker/code12#334]
On Dave's HP Folio 13 laptop (Windows 10 Pro), New Program doesn't work. The add-in function fileDialogs.inputBox() used for the initial program name query always returns false (as if cancelled).

**Comment by davecparker** [comment]
Fixed by removing the initial prompt for a program name and going straight to the Save As dialog with "MyProgram.java" as the suggested default. The name and extension are then checked afterwards, and overwriting an existing file is not allowed. 

Unfortunately the Save As dialog on both Mac and Windows has a built-in prompt to confirm overwriting a file, but if you confirm we just say we refuse afterwards in another alert. It's not super clean, but I'd rather have this than accidental overwrites by students.

**Comment by bcauchon** [comment]
Fix confirmed. Tested trying to overwrite an existing file (with and without extension), saving a file name with improper capitalization/characters, cancelling the Save As window, and saving a valid file name.
