### ISSUE TITLE
Options crashes trying to create scrollbar

### ISSUE THREAD

**Issue by davecparker** [davecparker/code12#339]
In a real build (not simulator),
1. Launch app
2. Resize app to be short vertically (enough so that Options would scroll)
3. Quit
4. Launch app (app remembers size and starts out short)
5. Press Options

This causes what look like Lua errors inside Corona (?):
* Attempt to index field 'parent' (a nil value) in _listener
* Attempt to call method 'insert' (a nil value) in createScrollBar called by _listener

On my Mac I was able to press "Continue" on these errors and then everything else seems to work.

**Comment by davecparker** [comment]
It appears you can continue, so hopefully not a fatal problem. Investigate only if/when you have time.

**Comment by bcauchon** [comment]
I created a new branch Ben-OptionsView and replaced the scrollView with a vertical scrollbar. Should I open a pull request or do you want to check it out first?

**Comment by bcauchon** [comment]
Should be fixed by #340 Ben-OptionsView: ScrollView replaced with Scrollbar
