### ISSUE TITLE
Windows version cannot open images from a flash drive

### ISSUE THREAD

**Issue by davecparker** [davecparker/code12#346]
If you try to run a Code12 program directly from a folder on a flash drive (or any drive other than C:), even when image files are copied properly to be there next to the .java file, ct.image() and others cannot find the images.

Students need to work around this by copying the folder to the desktop or somewhere on C:

**Comment by davecparker** [comment]
If we don't fix it, at least we should detect the situation and give a warning alert and/or warning console message at the ct.image/sound.

**Comment by davecparker** [comment]
Some hints where to find the relevant code:

Calls to ct.image() end up in GameObj.lua in GameObj:newImage(), which calls pathAndBaseDirForImage() to determine the "base dir" and a relative path.

The base dir is a constant indicating which one of Corona's special dirs to start from.
See https://docs.coronalabs.com/api/type/Constant.html
We currently use the "DocumentsDirectory" but there is also a temp dir option.

If you trace the functions used, you will find that this is currently working by consulting a table called appContext that contains the program's dir info stored in it. This was put in by app.processUserFile() in main.lua. The main function handling the nasty relative path is env.relativePath() in env.lua, which has a couple of TODO comments predicting this bug...

Note that this all is only a problem on Windows. Mac has no drive letters. Everything is relative to the main root at /.

**Comment by davecparker** [comment]
Another Corona function you will want to use is system.pathForFile():
https://docs.coronalabs.com/api/library/system/pathForFile.html

**Comment by davecparker** [comment]
If you're done with this now, enter your comments in here on what the fix was, mark it fixed, and assign to me to verify.

**Comment by bkainoa** [comment]
This has been fixed

**Comment by davecparker** [comment]
Looks good on both Mac and Windows.
