### ISSUE TITLE
Should ct.pause() show an alert instead of console text?

### ISSUE THREAD

**Issue by davecparker** [davecparker/code12#358]
Instead of printing red warning text to the console, perhaps ct.pause() should show an alert, to make it more visible and obvious.

The simplest thing would be a simple alert (e.g. "Paused at line 46") with just an OK button, which just dismisses the alert but stays paused (then the user picks from buttons in the toolbar). Or perhaps choices such as OK and Resume.

Perhaps ditto for ct.stop().

**Comment by bkainoa** [comment]
Got the alert message working for ct.pause();
