### ISSUE TITLE
'.' in GameObj fields in watch window

### ISSUE THREAD

**Issue by landonfox00** [davecparker/code12#387]
In the watch window, under the attributues of a GameObj it lists items such as '.x', '.y', '.id', and 'group'. Only some fields hold a '.' prefix, is this used to represent a user accessible data field? If so, should 'group' also have a '.'?

Here's a screenshot from my vector use case test.
![Capture](https://user-images.githubusercontent.com/23734685/59001786-d184ec80-87c4-11e9-9ed7-e9902fbdf9fc.PNG)

**Comment by davecparker** [comment]
Yes this is a bug. In varWatch.lua, numPublicGameObjFields needs to be 5 now, not 4. Go ahead and change this.
