### ISSUE TITLE
Highlight placement in varied fonts

### ISSUE THREAD

**Issue by landonfox00** [davecparker/code12#392]
Highlights within the source code error display are in the wrong position for fonts 12 and 18 in Windows. Fonts 14, 20 and 24 all work perfectly. The placement within 12 and 18 is always after the location of the error in the line, longer the line, the further the highlight is placed from its correct placement. 
- Some examples of source code errors:
    - Missing semi-colon:
        - Font 12:
![semi_colon_font12](https://user-images.githubusercontent.com/23734685/59948331-91f50c00-9424-11e9-8837-ee15d63ffd4e.PNG)
        - Font 14:
![semi_colon_font14](https://user-images.githubusercontent.com/23734685/59948343-99b4b080-9424-11e9-9204-ad9a3b906e5b.PNG)
        - Font 18:
![semi_colon_font18](https://user-images.githubusercontent.com/23734685/59948344-9c170a80-9424-11e9-9a11-87e5ca62fe96.PNG)
    - Undefined variable with lengthy statement:
        - Font 12:
![undef_var_font12](https://user-images.githubusercontent.com/23734685/59948345-9de0ce00-9424-11e9-9a85-e086dad850c4.PNG)
        - Font 14:
![undef_var_font14](https://user-images.githubusercontent.com/23734685/59948348-9f11fb00-9424-11e9-9371-56d66a0e7b15.PNG)
        - Font 18:
![undef_var_font18](https://user-images.githubusercontent.com/23734685/59948352-a0dbbe80-9424-11e9-93f0-c4a009f4a505.PNG)

**Comment by davecparker** [comment]
Not sure what is causing this, but it sure looks like cumulative round-off error of the average char width vs. the actual glyph locations as rendered. Our code appears to be handling the ave char width properly, and all the 5 average widths end up non-integer on Mac and all work fine on Mac.

**Comment by davecparker** [comment]
For now we will just remove the problematic sizes. Good news is these are not important sizes.
Fixed in optionsView by only offering sizes 14, 20, and 24.
