### ISSUE TITLE
onKeyPress/onKeyRelease Events: Can't test key names with ==

### ISSUE THREAD

**Issue by alias-nicole** [davecparker/code12#48]
Key names that appear not to work (when used as part of an if statement) in these two events:

- "a" to "z"  (alphabet keys)
- "0" to "9" (top row number keys)
- "tab"

However, they (except for "tab") work fine when used in part of a switch statement (see attached test belowfor further details).

`import Code12.*;
   
   public class MainProgram extends Code12Program
   {
      GameObj circle;
      
      public static void main(String[] args)
      { 
         Code12.run(new MainProgram()); 
      }
      
      public void start()
      {
         circle = ct.circle(ct.getWidth()/2, ct.getHeight()/2, 10 );   
      }
      
      
      public void onKeyPress(String keyName)
      {
         if ( keyName == "right" )  // works
            circle.xSpeed = 1;
            
          if ( keyName == "w" )      // does not work
            circle.xSpeed = -1;
            
        // But works as a switch statement
        switch (keyName)
        {
            case "d":
               circle.x += 5;
               break;
            case "a":
               circle.x -= 5;
        }
        
      }
      
      public void onKeyRelease(String keyName)
      {
         if ( keyName == "space" ) // this is one that works
            circle.ySpeed = 1;
   
         if ( keyName == "up" )   // also works      
            circle.ySpeed = -1;
            
         if ( keyName == "a" )   // does not work
            circle.ySpeed = 10;
         
         // works when used with a switch statement
         // this one tests top row number keys and tab
         switch ( keyName )
         {
            case "0":
               circle.y += 5;
               break;
            case "5":
               circle.y -= 5;
            case "tab":          // does not seem to work
               circle.y = 10;
         }
      }
      
   }
`

**Comment by davecparker** [comment]
Thanks for including the code, that is super helpful. Because keyName is a String, you can't reliably compare to another string with == but instead need to use keyName.equals("up"), which explains why it works in a switch. 

But this will be a common error for students, so my phase 2 system should detect and point out this issue. Changed status to work item for then.

**Comment by davecparker** [comment]
Nicole, assigning back to you to verify this for now. Assign back me when you've verified one way or another.

**Comment by alias-nicole** [comment]
Ah I see, I apologize for the rookie mistake. Verified that it does indeed work.

**Comment by davecparker** [comment]
The Lua runtime now supports str.equals() and also the Code12 app now considers use of == with Strings to be an error.

**Comment by alias-nicole** [comment]
Clarified the usage of == vs .equals
