### ISSUE TITLE
Font used by ct.text has different char width on Mac vs. Windows

### ISSUE THREAD

**Issue by davecparker** [davecparker/code12#55]
See Stopwatch use case test.

**Comment by davecparker** [comment]
Now using Verdana-Bold as the text object font on both Java and Lua, both Mac and Windows. Can you verify this works OK on Windows?

**Comment by bcauchon** [comment]
On Windows the char width seems to be larger when running Stopwatch.java through JGrasp than it does when running it through Corona. Also on the Corona Simulator it doesn't look Bold (though it does on the desktop build).

**Comment by bcauchon** [comment]
Fix verified. Font is slightly wider in Java build vs Corona, but Corona is consistent across platforms and simulator/desktop build.
