### ISSUE TITLE
Need to rename ct.round() with 2-parameters

### ISSUE THREAD

**Issue by davecparker** [davecparker/code12#70]
Right now we have:
    int ct.round( double d )
    double ct.round( double d, int numPlaces )

We need to rename the second of these to:
    double ct.roundDecimal( double d, int numPlaces )
because there can't be two functions with the same name but different return types.

**Comment by davecparker** [comment]
Fixed for both Java and Lua, please verify.

**Comment by bcauchon** [comment]
Fix verified in Java and Lua.
Still needs to be updated in API.md and API.html.

**Comment by davecparker** [comment]
Oops, docs updated, thanks.

**Comment by bcauchon** [comment]
Fix verified.
