### ISSUE TITLE
Need to set minimum window size

### ISSUE THREAD

**Issue by bcauchon** [davecparker/code12#71]

**Comment by davecparker** [comment]
Fixed in Code12 app, need to do for Java runtime too.

**Comment by davecparker** [comment]
I'll let you adjust this in the Code12 app so that the window is wide enough to show the getFile view (close now). This is minViewWidth in build.settings.
I don't think we care for the Java runtime, since it's all game graphics.

**Comment by bcauchon** [comment]
Should be fixed by merge pull request #246, commit 115a4e1
