### ISSUE TITLE
Passing null as String parameters

### ISSUE THREAD

**Issue by landonfox00** [davecparker/code12#74]
A NullPointerException is thrown when null is passed within the GameText constructor, GameImage constructor, align() method, and hit() method.

```
import Code12.*;
public class Test extends Code12Program
{
    public static void main(String[] args)
    {
        Code12.run(new Test());
    }

    public void start()
    {
        ct.text(null, 50, 50, 10, "red");
        ct.image(null, 50, 50, 10);
        GameObj text = ct.text("test", 50, 50, 10);
        text.align(null);
        text.hit(null);
    }
}
```

GameText:
![screenshot from 2018-06-19 14-11-29](https://user-images.githubusercontent.com/23734685/41624631-2fdfe4ce-73cb-11e8-932b-61743c37efca.png)

GameImage:
![screenshot from 2018-06-19 14-12-00](https://user-images.githubusercontent.com/23734685/41624637-37c7a74e-73cb-11e8-8673-2461311bd126.png)

align:
![screenshot from 2018-06-19 14-13-25](https://user-images.githubusercontent.com/23734685/41624645-3fb2ddca-73cb-11e8-9cc1-a41ac5a47117.png)

hit:
![screenshot from 2018-06-19 14-19-35](https://user-images.githubusercontent.com/23734685/41624884-d8ad0884-73cb-11e8-829d-33554489b8d6.png)

**Comment by davecparker** [comment]
Updated all APIs in both Java and Lua runtime to consider/protect against null String parameters. Some substitute empty string, some ignore the call, others like setFillColor use it to remove the fill.
