### ISSUE TITLE
Fields initialized inside functions register as un-initialized

### ISSUE THREAD

**Issue by bcauchon** [davecparker/code12#90]
"Variable x must be assigned before it is used"

**Comment by davecparker** [comment]
I've reworked some things internally, but this is probably still an issue. But I forget the repro case you had. Can you attach some code?

**Comment by bcauchon** [comment]
In GitHub\code12\Java\Random Walk\RandomWalk.java
```
   int pixelsPerSquare; // Dimension of the lattice grid
   ...
   public void start()
   {  
      restart();  
   }

   public void update()
   {
      ...
      int lineWidth = ct.round( pixelsPerSquare / 3.0 );
      ...
   }
   public void restart()
   {
      ...     
      // Initialize size variables
      pixelsPerSquare = 8;
      ...
   }
```

**Comment by davecparker** [comment]
Too hard to fix in general, and I like the aggressive error for Code12 students in most cases. We will require them to init the variable to something (e.g. 0) at the declaration in cases like this.

**Comment by bcauchon** [comment]
Sounds good.
